name: Node.js CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Build and test
      run: npm run start
    - name: git push
      run: npm run start
    - name: GIT commit and push all changed files
      env: 
        CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
        CI_COMMIT_AUTHOR: Continuous Integration
      run: |
        git config --global user.name "ci user"
        git config --global user.email "username@users.noreply.github.com"
        git commit -a -m "github actions run"
        git push
